import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faLaptopCode,
  faPalette,
  faChartLine,
  faPen,
  faVideo,
  faMobileAlt,
  faGlobe,
  faCamera,
  faMusic,
  faGamepad,
  faDumbbell,
  faUtensils,
  faHome,
  faCar,
  faPlane,
  faGraduationCap,
  faBriefcase,
  faHeart,
  faShoppingBag,
  faTools,
  faWrench,
  faPaintBrush,
  faCode,
  faDatabase,
  faCloud,
  faLock,
  faShield,
  faBell,
  faEnvelope,
  faPhone,
  faUser,
  faUsers,
  faFolder,
  faFile,
  faImage,
  faFilm,
  faBook,
  faNewspaper,
  faCalendar,
  faClock,
  faMapMarker,
  faSearch,
  faStar,
  faThumbsUp,
  faComment,
  faShare,
  faDownload,
  faUpload,
  faTrash,
  faEdit,
  faSave,
  faPlus,
  faMinus,
  faCheck,
  faTimes,
  faArrowRight,
  faArrowLeft,
  faBars,
  faCog,
  faQuestionCircle,
  faInfoCircle,
  faExclamationCircle,
  faCheckCircle,
  IconDefinition,
} from '@fortawesome/free-solid-svg-icons'

const iconMap: Record<string, IconDefinition> = {
  'fa-laptop-code': faLaptopCode,
  'fa-palette': faPalette,
  'fa-chart-line': faChartLine,
  'fa-pen': faPen,
  'fa-video': faVideo,
  'fa-mobile-alt': faMobileAlt,
  'fa-globe': faGlobe,
  'fa-camera': faCamera,
  'fa-music': faMusic,
  'fa-gamepad': faGamepad,
  'fa-dumbbell': faDumbbell,
  'fa-utensils': faUtensils,
  'fa-home': faHome,
  'fa-car': faCar,
  'fa-plane': faPlane,
  'fa-graduation-cap': faGraduationCap,
  'fa-briefcase': faBriefcase,
  'fa-heart': faHeart,
  'fa-shopping-bag': faShoppingBag,
  'fa-tools': faTools,
  'fa-wrench': faWrench,
  'fa-paint-brush': faPaintBrush,
  'fa-code': faCode,
  'fa-database': faDatabase,
  'fa-cloud': faCloud,
  'fa-lock': faLock,
  'fa-shield': faShield,
  'fa-bell': faBell,
  'fa-envelope': faEnvelope,
  'fa-phone': faPhone,
  'fa-user': faUser,
  'fa-users': faUsers,
  'fa-folder': faFolder,
  'fa-file': faFile,
  'fa-image': faImage,
  'fa-film': faFilm,
  'fa-book': faBook,
  'fa-newspaper': faNewspaper,
  'fa-calendar': faCalendar,
  'fa-clock': faClock,
  'fa-map-marker': faMapMarker,
  'fa-search': faSearch,
  'fa-star': faStar,
  'fa-thumbs-up': faThumbsUp,
  'fa-comment': faComment,
  'fa-share': faShare,
  'fa-download': faDownload,
  'fa-upload': faUpload,
  'fa-trash': faTrash,
  'fa-edit': faEdit,
  'fa-save': faSave,
  'fa-plus': faPlus,
  'fa-minus': faMinus,
  'fa-check': faCheck,
  'fa-times': faTimes,
  'fa-arrow-right': faArrowRight,
  'fa-arrow-left': faArrowLeft,
  'fa-bars': faBars,
  'fa-cog': faCog,
  'fa-question-circle': faQuestionCircle,
  'fa-info-circle': faInfoCircle,
  'fa-exclamation-circle': faExclamationCircle,
  'fa-check-circle': faCheckCircle,
}

export function getIconFromName(iconName?: string): IconDefinition | null {
  if (!iconName) return null
  return iconMap[iconName] || null
}

export function renderIcon(iconName?: string, className?: string) {
  const icon = getIconFromName(iconName)
  if (icon) {
    return <FontAwesomeIcon icon={icon} className={className} />
  }
  // If it's not a FontAwesome icon name, treat it as emoji/text
  return iconName ? <span className={className}>{iconName}</span> : null
}

